version: 2.1
jobs:
  build:
    docker:
      - image: ruby:3.0.3
    steps:
      - checkout
      - run:
          name: Run the default task
          command: |
            gem install bundler -v 2.3.17
            bundle install
            bundle exec rake
